---
title: "Amazon_fifth_category_PENCIL#group_(Mijares_Mabalina_Compay)"
author: "Mijares_Mabalina_Compay"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(polite)
library(kableExtra)
library(rmarkdown)
library(httr)
library(rvest)
library(dplyr)
library(stringr)
library(ggplot2)
library(knitr)
```

```{r}
urls5 <- c('https://www.amazon.com/AmazonBasics-Pre-sharpened-Wood-Cased-Pencils/dp/B071JM699P/ref=sr_1_5?crid=23CVTGNFBSJ7H&dib=eyJ2IjoiMSJ9.3ppF-cpAcuQGvUW6cmKQ9sfSyMf-rq6O-ewUCcyBtq1tPyc43_s0h7_j7mC0tJqkx8jXcdC3aWJGhdETeBQ5qdgAmhuEgkKUOdG6ll1hAvxPNo2YL-uWCX1-5ZCs4a-usUWV07U5YV1fdOE98238WsChq_om8naKcDpKsbDAyltaAqacXseyfD752JEdomO6pA9Mk1SI8M4ISiLOG1YgKScQ19ZoNbZXRfAMuUUsGcZEBD4eDL6VIPu2fT9GQoaoB8YxycteenYOltG9_vTWanJm2q_TSn25PP2x7fU1FCE.s6t607qIFuL8HPvIasqrKoMPWy8b_-pi0k0Fbdnq-pQ&dib_tag=se&keywords=Amazon+Basics+Woodcased+Classroom+%232+Pencils+with+Er&qid=1733880590&sprefix=westcott+10381+wooden+ruler%2C+12+inch%2C+assorted+colors%2Caps%2C864&sr=8-5', 
           'https://www.amazon.com/Wood-Cased-Pencils-Pre-sharpened-pencils-Madisi/dp/B07NW9N6W5/ref=sr_1_5?dib=eyJ2IjoiMSJ9.uL1zvRhyMHj_-xIjAIL4zLulgcgwR2wlvvnO9z7Kdd3OcalJT9ork9-NmjAM8riN9ZRqSyI4TMy6YOLl79jONfc_eGjuesh-3tHmHToDTHj_89Vq3cK4BAyD79_CriBPV6JA7hUh337V4HOzPZ50ILiW87CF38R8V-IlyC0E1DGuey9AB9vto8tTO6BMYhbHPGMUOKg-v8yI0LwHFq5hXhvOJEO_6FL84NuzdfbOf3vDJSR7I3Y8LN9x7C1HflSE3hIdJmeyqo-GUlUMrEYzxHzPkua_8-2niZ7BjIcGTmY.2Tgs9cVKxM2Sw7llNQoq_GZdNf9dyHHr8VeNEVe0j3E&dib_tag=se&keywords=Madisi+Wood-Cased+%232+HB+Pencils%2C+Yellow%2C+Pre-sharpen&qid=1733880622&sr=8-5',
           'https://www.amazon.com/Hapikalor-360-Pack-Sharpened-Classroom-Sketching/dp/B0D337KRQQ/ref=sr_1_5?crid=J2IJJSAFP2YK&dib=eyJ2IjoiMSJ9.bpr2CbYOOJfh_vxvnt3MGxlKlpMx8mr_rRfyXeSKcCPeXYB2LPJurGd0fjs3xpE6hpBha-gy4oGnkXiXvVDQS_NrM_Ofn0zuwcBYAcqLKRdQqR-NiXHDU9kLgX9idLJ3ZJm4WgYqEA1Ogopib-vQAbX8oMBSEuDG3UCaUg4UOu_CKsUZIKp9sVzi6aunwMRQwRJ-l-YfySNHVOYfkzAhGzOKkik9eSAwEf1tgPYuddZ_O4rJlBfe_iN3132I-kfz4aDf6mZl8xyXHbxwBTs4tKtQEZG51gtbwuXbJqcMWIM.sAQLxhKZIXijtzdTIdeLwspvyXmMyYaIgYF44KW28tA&dib_tag=se&keywords=360-Pack+Sharpened+%232+Yellow+Pencils+with+Erasers%2C+Bulk&qid=1733880639&sprefix=360-pack+sharpened+2+yellow+pencils+with+erasers%2C+bulk%2Caps%2C393&sr=8-5', 
           'https://www.amazon.com/AmazonBasics-Pre-sharpened-Wood-Cased-Pencils/dp/B071JM699P/ref=sr_1_5?crid=2ZOA4B8BLOFRE&dib=eyJ2IjoiMSJ9.ipF6Nb_jyPvG8pTjlLapGE4o0-G9g6u7Ra9h2pskVzRwVKF8M3SkZShFYXrVnoP0lD6rzldFmGHq8e9VA0lubM-tG-oKiFIE_zCaAcpiU-L_eaTL6BB43g2sUzmzwpCTV6JA7hUh337V4HOzPZ50IBkSznk6g680kr1JrWHb8mie01-6axqaiAUWcOB2WAOuCMDnaXTv-FFFBPLmSLQHfQQQ2gj5iiY-BmiN9Tcg-hOzDlYsn5MB-TiUOiK0HIFci_rLxnsA7r3-0yejnuHCXStwedX5_L4DxjEd1OcZDpM.YbnRZM-uFVwKIbZitzXUt0_C1NjpdHxQmnzg48hbj6w&dib_tag=se&keywords=Amazon+Basics+Wood-Cased+%232+Pencils%2C+Pre-sharpened%2C&qid=1733880675&sprefix=amazon+basics+wood-cased+2+pencils%2C+pre-sharpened%2C+%2Caps%2C323&sr=8-5', 
           'https://www.amazon.com/Prismacolor-Premier-Colored-Pencils-Assorted/dp/B00006IEEU/ref=sr_1_1?crid=1F8AN6PYN5Y8&dib=eyJ2IjoiMSJ9.4DxnhyVPwDoCAY6Rws6D0B9n-stym3oMvRPVBT3x9sJGU3XM2ni9D241su2m-ATJxgVaSO46TX67xil8O_YpOHS7UnK--LlGBKDIuItOAOT9zy6f0J09cV9j0mWfClFhvrrJcNf7W8sdL0m7kPdVW_NEfcmCA7KETgJYrGEJJ9NGwATJ6xzI5ar_4Rz5GBZv5Cw34KPgsmfWOWAPKhM28AmJ5Akyb9mOpzW6fJdRr3fO0IMpl-cOiEoPTCWtv--i2Y6HsRRfNG50EsTpEYGCua2KFVn5vlvi588AdVpLQqU.w5cxOemTR18e2vad8SN_1i1oVkz6BzuqJQ7QsiBwWks&dib_tag=se&keywords=prismacolor+premier+colored+pencils%2C+soft+core%2C+24+pack&qid=1733880693&sprefix=prismacolor+premier+colored+pencils%2C+soft+core%2C+24+pack%2Caps%2C305&sr=8-1')
nameofproduct5 <-vector("list", length(urls5))
names5 <- vector("list", length(urls5))
ratings5 <- vector("list", length(urls5))
dates5 <- vector("list", length(urls5))
title5 <- vector("list", length(urls5))
text5 <- vector("list", length(urls5))
n5 <- vector("list", length(urls5))
```

```{r}
df <- list()
for (i in seq_along(urls5)) {
    session <- bow(urls5[i], user_agent = "Educational")
  webpage5 <- scrape(session)
  nam5 <-webpage5 %>% html_nodes(".a-profile-name") %>% html_text()
  nam5 <- nam5[!grepl("hair care routine for BROKEN DAMAGED hair|Amazon Customer", nam5, ignore.case = TRUE)]
    nam5 <- nam5[nam5 != ""]
    n5[[i]] <- nam5
    name5 <- c() 
    non_amazon_seen5 <- FALSE  
    for (na5 in nam5) {
      if (na5 == "Amazon Customer") {
        if (non_amazon_seen5) {
          name5 <- c(name5, na5)
        }
      } else {
        name5 <- c(name5, na5)
        non_amazon_seen5 <- TRUE
        }
    }
    name5 <- name5[!duplicated(name5) | name5 == "Amazon Customer"]
    names5[[i]] <- name5
    
        nameofproduct5[[i]] <-  webpage5 %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct5[[i]] <- rep(nameofproduct5[[i]], length.out = length(names5[[i]]))
    
    rate5 <- webpage5 %>% html_nodes(".a-icon-alt") %>% html_text()
    rati5 <- rate5[!grepl("Previous page of related Sponsored Products|Next page of related Sponsored Products|Previous page|Next page", rate5, ignore.case = TRUE)]
    rat5 <- gsub(" out of 5 stars", "", rati5)
    rats5 <- rat5
    if (length(rats5) > length(name5)) {
    rats5 <- tail(rats5, length(name5)) 
    } else if (length(rats5) < length(name5)) {
    rats5 <- c(rats5, rep(NA, length(name5) - length(rats5)))
    }
    ratings5[[i]] <- rats5
    
    dat5 <- webpage5 %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date5 <- gsub("Reviewed.*on ", "", dat5)
    dates5[[i]] <- date5
    titl5 <- webpage5 %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit5 <- gsub("Reviewed.*on ", "", titl5)
    ti5 <- gsub(".*stars\\s*", "", tit5)
    t5 <- gsub("\\s+", " ", ti5)
    title5[[i]] <- t5
    tex5 <- webpage5 %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te5 <- gsub("\\n", " ", tex5)
    t5 <- gsub("\\s+", " ", te5)
    text5[[i]] <- trimws(t5)
}
```

```{r}
cate5 <- c("Category 1: WATCH", "Category 2: CANVAS", "Category 3: PAINT", "Category 4: RULER", "Category 5: PENCIL")
category5 <- vector("list", length(cate5))
for (i in seq_along(cate5)) {
    category5[[i]] <- cate5[i]
}
```

```{r}
for (i in seq_along(urls5)) {
    category5[[i]] <- rep(category5[[i]], length.out = length(names5[[i]]))
}
```

```{r}
productnumbe5 <- c("Product 1", "Product 2", "Product 3", "Product 4", "Product 5")
productnumber5 <- vector("list", length(productnumbe5))
for (i in seq_along(productnumbe5)) {
    productnumber5[[i]] <- productnumbe5[i]
}
for (i in seq_along(urls5)) {
    productnumber5[[i]] <- rep(productnumber5[[i]], length.out = length(names5[[i]]))
}
```

```{r}
nama5 <- names5[[1]]
namez5 <- nama5[!grepl("A Closer Look|Genuine Insight & Practical Perspective", nama5, ignore.case = TRUE)]
namez5 <- unique(namez5)
namez5 <- namez5[-1]
producto5 <- productnumber5[[1]]
producto5 <- rep(producto5, length.out = length(namez5))
produc5 <- nameofproduct5[[1]]
produc5 <- rep(produc5, length.out = length(namez5))
cater5 <- category5[[5]]
ca5 <- rep(cater5, length.out = length(namez5))
ratingz5 <- ratings5[[1]]
    if (length(ratingz5) > length(namez5)) {
    ratingz5 <- tail(ratingz5, length(namez5)) 
    } else if (length(ratingz5) < length(namez5)) {
    ratingz5 <- c(ratingz5, rep(NA, length(namez5) - length(ratingz5)))
    }
```
```{r}
max_length <- max(
  length(ca5),
  length(producto5),
  length(produc5),
  length(namez5),
  length(ratingz5),
  length(dates5[[1]]),
  length(title5[[1]]),
  length(text5[[1]])
)

ca5 <- c(ca5, rep(NA, max_length - length(ca5)))
producto5 <- c(producto5, rep(NA, max_length - length(producto5)))
produc5 <- c(produc5, rep(NA, max_length - length(produc5)))
namez5 <- c(namez5, rep(NA, max_length - length(namez5)))
ratingz5 <- c(ratingz5, rep(NA, max_length - length(ratingz5)))
dates5[[1]] <- c(dates5[[1]], rep(NA, max_length - length(dates5[[1]])))
title5[[1]] <- c(title5[[1]], rep(NA, max_length - length(title5[[1]])))
text5[[1]] <- c(text5[[1]], rep(NA, max_length - length(text5[[1]])))

pencil1 <- data.frame(Category = ca5,
                     Product_number = producto5,
                     Name_of_Product = produc5,
                     Userame = namez5,
                     Rating = ratingz5,
                     Date = dates5[[1]],
                     Title_of_Review = title5[[1]],
                     Text_of_Review = text5[[1]],
                     stringsAsFactors = FALSE)

head(pencil1, 50)
pencil1 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama52 <- names5[[1]]
name52 <- nama52[!grepl("A Closer Look", nama52, ignore.case = TRUE)]
namez52 <- unique(namez5)
namez52 <- namez52[-(2:2)]
producto52 <- productnumber5[[2]]
producto52 <- rep(producto52, length.out = length(namez52))
produc52 <- nameofproduct5[[2]]
produc52 <- rep(produc52, length.out = length(namez52))
cater52 <- category5[[5]]
ca52 <- rep(cater52, length.out = length(namez52))
ratingz52 <- ratings5[[2]]
    if (length(ratingz52) > length(namez52)) {
    ratingz52 <- tail(ratingz52, length(namez52)) 
    } else if (length(ratingz52) < length(namez52)) {
    ratingz52 <- c(ratingz52, rep(NA, length(namez52) - length(ratingz52)))
    }
```

```{r}
max_length <- max(
  length(ca52),
  length(producto52),
  length(produc52),
  length(namez52),
  length(ratingz52),
  length(dates5[[2]]),
  length(title5[[2]]),
  length(text5[[2]])
)

ca52 <- c(ca52, rep(NA, max_length - length(ca52)))
producto52 <- c(producto52, rep(NA, max_length - length(producto52)))
produc52 <- c(produc52, rep(NA, max_length - length(produc52)))
namez52 <- c(namez52, rep(NA, max_length - length(namez52)))
ratingz52 <- c(ratingz52, rep(NA, max_length - length(ratingz52)))
dates5[[2]] <- c(dates5[[2]], rep(NA, max_length - length(dates5[[2]])))
title5[[2]] <- c(title5[[2]], rep(NA, max_length - length(title5[[2]])))
text5[[2]] <- c(text5[[2]], rep(NA, max_length - length(text5[[2]])))
pencil2 <- data.frame(Category = ca52,
                     Product_number = producto52,
                      Name_of_Product = produc52,
                      Userame = namez52,
                       Rating = ratingz52,
                       Date = dates5[[2]],
                       Title_of_Review = title5[[2]],
                       Text_of_Review = text5[[2]],
                       stringsAsFactors = FALSE
                       )
head(pencil2, 50)
pencil2 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama53 <- names5[[3]]
namez53 <- nama53[!grepl("360-Pack Sharpened #2 Yellow Pencils for School Supplies", nama53, ignore.case = TRUE)]
namez53 <- namez53[-(1:2)]
namez53 <- unique(namez53)
producto53 <- productnumber5[[3]]
producto53 <- rep(producto53, length.out = length(namez53))
produc53 <- nameofproduct5[[3]]
produc53 <- rep(produc53, length.out = length(namez53))
cater53 <- category5[[5]]
ca53 <- rep(cater53, length.out = length(namez53))
ratingz53 <- ratings5[[3]]
    if (length(ratingz53) > length(namez53)) {
    ratingz53 <- tail(ratingz53, length(namez53)) 
    } else if (length(ratingz53) < length(namez53)) {
    ratingz53 <- c(ratingz53, rep(NA, length(namez53) - length(ratingz53)))
    }
```
```{r}
max_length <- max(
  length(ca53),
  length(producto53),
  length(produc53),
  length(namez53),
  length(ratingz53),
  length(dates5[[3]]),
  length(title5[[3]]),
  length(text5[[3]])
)

ca53 <- c(ca53, rep(NA, max_length - length(ca53)))
producto53 <- c(producto53, rep(NA, max_length - length(producto53)))
produc53 <- c(produc53, rep(NA, max_length - length(produc53)))
namez53 <- c(namez53, rep(NA, max_length - length(namez53)))
ratingz53 <- c(ratingz53, rep(NA, max_length - length(ratingz53)))
dates5[[3]] <- c(dates5[[3]], rep(NA, max_length - length(dates5[[3]])))
title5[[3]] <- c(title5[[3]], rep(NA, max_length - length(title5[[3]])))
text5[[3]] <- c(text5[[3]], rep(NA, max_length - length(text5[[3]])))

pencil3 <- data.frame(Category = ca53,
                     Product_number = producto53,
                      Name_of_Product = produc53,
                      Userame = namez53,
                       Rating = ratingz53,
                       Date = dates5[[3]],
                       Title_of_Review = title5[[3]],
                       Text_of_Review = text5[[3]],
                       stringsAsFactors = FALSE
                       )
head(pencil3, 50)
pencil3 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama54 <- names5[[4]]
namez54 <- nama54[!grepl("Genuine Insight & Practical Perspective", nama54, ignore.case = TRUE)]
namez54 <- namez54[-(1:2)]
namez54 <- unique(namez54)
producto54 <- productnumber5[[4]]
producto54 <- rep(producto54, length.out = length(namez54))
produc54 <- nameofproduct5[[4]]
produc54 <- rep(produc54, length.out = length(namez54))
cater54 <- category5[[4]]
ca54 <- rep(cater54, length.out = length(namez54))
ratingz54 <- ratings5[[4]]
    if (length(ratingz54) > length(namez54)) {
    ratingz54 <- tail(ratingz54, length(namez54)) 
    } else if (length(ratingz54) < length(namez54)) {
    ratingz54 <- c(ratingz54, rep(NA, length(namez54) - length(ratingz54)))
    }
```
```{r}
max_length <- max(
  length(ca54),
  length(producto54),
  length(produc54),
  length(namez54),
  length(ratingz54),
  length(dates5[[4]]),
  length(title5[[4]]),
  length(text5[[4]])
)

ca54 <- c(ca54, rep(NA, max_length - length(ca54)))
producto54 <- c(producto54, rep(NA, max_length - length(producto54)))
produc54 <- c(produc54, rep(NA, max_length - length(produc54)))
namez54 <- c(namez54, rep(NA, max_length - length(namez54)))
ratingz54 <- c(ratingz54, rep(NA, max_length - length(ratingz54)))
dates5[[4]] <- c(dates5[[4]], rep(NA, max_length - length(dates5[[4]])))
title5[[4]] <- c(title5[[4]], rep(NA, max_length - length(title5[[4]])))
text5[[4]] <- c(text5[[4]], rep(NA, max_length - length(text5[[4]])))

pencil4 <- data.frame(Category = ca54,
                     Product_number = producto54,
                      Name_of_Product = produc54,
                      Userame = namez54,
                       Rating = ratingz54,
                       Date = dates5[[4]],
                       Title_of_Review = title5[[4]],
                       Text_of_Review = text5[[4]],
                       stringsAsFactors = FALSE
                       )
head(pencil4, 50)
pencil4 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama55 <- names5[[5]]
namez55 <- nama55[!grepl("Prismacolor Premier Product Line", nama55, ignore.case = TRUE)]
namez55 <- namez55[-(1:2)]
namez55 <- unique(namez55)
producto55 <- productnumber5[[5]]
producto55 <- rep(producto55, length.out = length(namez55))
produc55 <- nameofproduct5[[5]]
produc55 <- rep(produc55, length.out = length(namez55))
cater55 <- category5[[5]]
ca55 <- rep(cater55, length.out = length(namez55))
ratingz55 <- ratings5[[5]]
    if (length(ratingz55) > length(namez55)) {
    ratingz55 <- tail(ratingz55, length(namez55)) 
    } else if (length(ratingz55) < length(namez55)) {
    ratingz55 <- c(ratingz55, rep(NA, length(namez55) - length(ratingz55)))
    }
```
```{r}
max_length <- max(
  length(ca55),
  length(producto55),
  length(produc55),
  length(namez55),
  length(ratingz55),
  length(dates5[[5]]),
  length(title5[[5]]),
  length(text5[[5]])
)

ca55 <- c(ca55, rep(NA, max_length - length(ca55)))
producto55 <- c(producto55, rep(NA, max_length - length(producto55)))
produc55 <- c(produc55, rep(NA, max_length - length(produc55)))
namez55 <- c(namez55, rep(NA, max_length - length(namez55)))
ratingz55 <- c(ratingz55, rep(NA, max_length - length(ratingz55)))
dates5[[5]] <- c(dates5[[5]], rep(NA, max_length - length(dates5[[5]])))
title5[[5]] <- c(title5[[5]], rep(NA, max_length - length(title5[[5]])))
text5[[5]] <- c(text5[[5]], rep(NA, max_length - length(text5[[5]])))

pencil5 <- data.frame(Category = ca55,
                     Product_number = producto55,
                      Name_of_Product = produc55,
                      Userame = namez55,
                       Rating = ratingz55,
                       Date = dates5[[5]],
                       Title_of_Review = title5[[5]],
                       Text_of_Review = text5[[5]],
                       stringsAsFactors = FALSE
                       )
head(pencil5, 50)
pencil5 %>% kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
urls5b <- c('https://www.amazon.com/TEACHERS-Woodcased-Pencils-Pre-sharpened-Erasers/dp/B0CY51CD7G/ref=sr_1_1?crid=9C0Z35SX6OVO&dib=eyJ2IjoiMSJ9.HwSkKbCMcJgJpFR80R72XpEKHRydJuUs3m6631LWHHAWAnnrjJYKySJ26SX5hTAHVqzVoo-K3P7OjNCnGyCFuTc6Gb7gCoLjbGemWD7hASjKIAnfgCEJepnVx8D5_Ov3csqtQHx1gcFlVr0LxocUPpGRhuCqMT1GIRLVzBQ20MgvF9MkAiFfb3voqyC-b44OMTElTMuJkQwzNw-_FO-s2te4H_SylUwNlapXsP-AcXJPWWatKRbpeD1rS3FmWeyE9gpqtL1hG16aC8rckylH22knJQBxZ1obN8wDWTKTo6I.3KP2DGTzrv9w0s6jtMO3hiHGNkQ17sfvlrWcJ2fAGek&dib_tag=se&keywords=S+%26+E+TEACHER%27S+EDITION+Woodcased+%232+Pencils%2C+Pre-sha&qid=1733882361&sprefix=s+%26+e+teacher%27s+edition+woodcased+2+pencils%2C+pre-sha%2Caps%2C701&sr=8-1',
            'https://www.amazon.com/SKKSTATIONERY-Assorted-Colorful-Assortment-Incentives/dp/B07BWK9P5P/ref=sr_1_5?crid=18PKSO6ZR1TJO&dib=eyJ2IjoiMSJ9.SyOnpuXobvKD3yAqb5noleaIvwg6hwbSi01TPCWxSuPfRQxrs72t7H6Vgp2mayNCewfPjaSzdAzDe--rtlH8aI3uL_IVtChqClMrnNA6-JNofzhl5a405bkL0n6Tw984SEoOoB6N9GD3P2FRXLtyyIYtLIvWQdIqFhlfj9-MbjM2VqmNNF_DXHp94X8BLMC2v7cbNbOcQKOtCfsfAKrpP3EM4Vb1KBsfyrVQgxDRNXZ524tOh7m2AKSq-m7nuBa1T8s3aqMljWBnALyP1EqO8BEI_fXBVyljwId3TEtKUY8.HxlQAGy08dm0FDBUypq5khbAR_OlGHzFA9Ik_hZYkEQ&dib_tag=se&keywords=SKKSTATIONERY+Assorted+Colorful+Pencils%2C+Wooden+Pencil+with+Eraser%2C+Pencil+Assortment%2C+Novelty+Kids+Pencils%EF%BC%8CAwards+%26+Incentives+Pencils%2C+2+HB%2C+12+Assorted+Colors+144%2Fbox.&qid=1733882401&sprefix=skkstationery+assorted+colorful+pencils%2C+wooden+pencil+with+eraser%2C+pencil+assortment%2C+novelty+kids+pencils+awards+%26+incentives+pencils%2C+2+hb%2C+12+assorted+colors+144%2Fbox.+%2Caps%2C386&sr=8-5',
            'https://www.amazon.com/BIC-Mechanical-Pencil-40-Count-MPCE40-BLK/dp/B08MQRQTKJ/ref=sr_1_1?dib=eyJ2IjoiMSJ9.ZMANWUVFXdyJT_dLyqeBDfTga_B0ApNoj6Yp4YwOlfVNe97Hgd4gT4l_fGLiUgzJ3t1jP64_Kt9RfMXHWuLg00Duc5Iil9ivJ_6LFllAJEycsJmwgEi8Tbeezek_doHAAXhInMDTLBrhlnLvXUqh1_LYXDD064BOElzl4PO9JjY9ATzCMCKyRP79GrfQtYnYXDC7VIxn9FTTzbIfjUJaK25GY-dNXcZCzrzc4j_VfF7jkMEFqeA3pP9Dc_uJxLEM0KRBnTVEoiRA2bsv-2H_4sw17F8GPjN1o-lQvp-H7ls.3I0fggX6fUK5wtonHU-15PcbLD6DT3IiOdcz7D079ns&dib_tag=se&keywords=BIC+Xtra+Smooth+Mechanical+Pencils+with+Erasers%2C+Bright&qid=1733882425&sr=8-1',
            'https://www.amazon.com/Crayola-Twistables-Colored-Exclusive-Stocking/dp/B07D4RN9NH/ref=sr_1_1?crid=2T20U2F1WJQLQ&dib=eyJ2IjoiMSJ9.3g_5Mj2JwaSob7TfAP7YSvpeoV5sQM3T8_mfdrLzTAZKyBuS4MFyB_V1XK4cO32yn6qSzCpWKID-rNtjb_SVyBmXHf6vTn4JTYdACYnzWrWlU0cq1N1pgldq8A6U7WKxeDVG5NIhZtmt51zfIiInsvqkbegIPE7rvPuPE1EiQUW-VXHwjDhurYx-cbJE1b3TgpbzCJbmYIcmgwpzfALaKu-_SjVwwjkeMUIfqUVyBWK0SIOw_rydGa3w9AvOd_UE1CCqJtXxSmUxJ85COGDgpv0FtGTqZSsDur_8QX7FRMg.0HhPXN0allP9UqQFGIVrnn-ZDK5o2u6YEUU40ExoiSQ&dib_tag=se&keywords=Crayola+Twistables+Colored+Pencil+Set+%2850ct%29%2C+No+Sharpen+Colored+Pencils+For+Kids%2C+Coloring+Book+Pencils%2C+Stocking+Stuffers+for+Kids%2C+Holiday+Gift%2C+4%2B&qid=1733884892&sprefix=ticonderoga+wood-cased+pencils%2C+pre-sharpened%2C+2+hb+soft%2C+yellow%2C+72+count%2Caps%2C788&sr=8-1',
            'https://www.amazon.com/Ticonderoga-Pre-Sharpened-Pencil-Eraser-Pack/dp/B079STQWBM/ref=sr_1_1?crid=17RGS6REQNC1Z&dib=eyJ2IjoiMSJ9.bJTERRcfS_-p9z_xB32Ry9-5CKMLmZDdXLruSHHCfnZBgC0VekPFOTDvqsq8Vw6tPoVq2j2ikqKRz1dtrV2PGfJkp_ActC5VuazaHLZTtiDvLnwZiNrcjIne0lT-ifOEcf5rpZup5-t38fb-X4qeED3e7LIZxjLnrJg4X1G6wobfANpls7AHMTdeB7UxSUlNpQ8rTjBWeIjShwIzxlTkAyj8_a_JI2Z5cXVVSlK8mgoHYffKsnnOlnHK6LRqQzBhPOMqVYEzuVaCcQZsPhoRavp-_6ftptl0Ifkwyo8rYBY.xLl1s-hvJMD4vERs_-5GftPBGqRmrAWG46UgndnEgas&dib_tag=se&keywords=Ticonderoga+Wood-Cased+Pencils%2C+Pre-Sharpened%2C+2+HB+Soft%2C+Yellow%2C+72+Count&qid=1733882472&sprefix=ticonderoga+wood-cased+pencils%2C+pre-sharpened%2C+2+hb+soft%2C+yellow%2C+72+count+%2Caps%2C313&sr=8-1')

nameofproduct5b <-vector("list", length(urls5b))
names5b <- vector("list", length(urls5b))
ratings5b <- vector("list", length(urls5b))
dates5b <- vector("list", length(urls5b))
title5b <- vector("list", length(urls5b))
text5b <- vector("list", length(urls5b))
n5b <- vector("list", length(urls5b))
```

```{r}
df <- list()
for (i in seq_along(urls5b)) {
    session <- bow(urls5b[i], user_agent = "Educational")
  webpage5b <- scrape(session)
  nam5b <-webpage5b %>% html_nodes(".a-profile-name") %>% html_text()
  nam5b <- nam5b[!grepl("hair care routine for BROKEN DAMAGED hair|Amazon Customer", nam5b, ignore.case = TRUE)]
    nam5b <- nam5b[nam5b != ""]
    n5b[[i]] <- nam5b
    name5b <- c() 
    non_amazon_seen5b <- FALSE  
    for (na5b in nam5b) {
      if (na5b == "Amazon Customer") {
        if (non_amazon_seen5b) {
          name5b <- c(name5b, na5b)
        }
      } else {
        name5b <- c(name5b, na5b)
        non_amazon_seen5b <- TRUE
        }
    }
    name5b <- name5b[!duplicated(name5b) | name5b == "Amazon Customer"]
    names5b[[i]] <- name5b
    
        nameofproduct5b[[i]] <-  webpage5b %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct5b[[i]] <- rep(nameofproduct5b[[i]], length.out = length(names5b[[i]]))
    
    rate5b <- webpage5b %>% html_nodes(".a-icon-alt") %>% html_text()
    rati5b <- rate5b[!grepl("Previous page of related Sponsored Products|Next page of related Sponsored Products|Previous page|Next page", rate5b, ignore.case = TRUE)]
    rat5b <- gsub(" out of 5 stars", "", rati5b)
    rats5b <- rat5b
    if (length(rats5b) > length(name5b)) {
    rats5b <- tail(rats5b, length(name5b)) 
    } else if (length(rats5b) < length(name5b)) {
    rats5b <- c(rats5b, rep(NA, length(name5b) - length(rats5b)))
    }
    ratings5b[[i]] <- rats5b
    
    dat5b <- webpage5b %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date5b <- gsub("Reviewed.*on ", "", dat5b)
    dates5b[[i]] <- date5b
    titl5b <- webpage5b %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit5b <- gsub("Reviewed.*on ", "", titl5b)
    ti5b <- gsub(".*stars\\s*", "", tit5b)
    t5b <- gsub("\\s+", " ", ti5b)
    title5b[[i]] <- t5b
    tex5b <- webpage5b %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te5b <- gsub("\\n", " ", tex5b)
    t5b <- gsub("\\s+", " ", te5b)
    text5b[[i]] <- trimws(t5b)
}
```

```{r}
cate5 <- c("Category 1: WATCH", "Category 2: CANVAS", "Category 3: PAINT", "Category 4: RULER", "Category 5: PENCIL")
category5b <- vector("list", length(cate5))
for (i in seq_along(cate5)) {
    category5b[[i]] <- cate5[i]
}
```

```{r}
for (i in seq_along(urls5b)) {
    category5b[[i]] <- rep(category5b[[i]], length.out = length(names5b[[i]]))
}
```

```{r}
productnumbe5b <- c("Product 6", "Product 7", "Product 8", "Product 9", "Product 10")
productnumber5b <- vector("list", length(productnumbe5b))
for (i in seq_along(productnumbe5b)) {
    productnumber5b[[i]] <- productnumbe5b[i]
}
for (i in seq_along(urls5b)) {
    productnumber5b[[i]] <- rep(productnumber5b[[i]], length.out = length(names5b[[i]]))
}
```

```{r}
namez5b <- names5b[[1]]
namez5b <- namez5b[!grepl("Wooden Pencils with Eraser Tops", namez5b, ignore.case = TRUE)]
namez5b <- unique(namez5b)
namez5b <- namez5b[-1]

producto5b <- productnumber5b[[1]] 
producto5b <- rep(producto5b, length.out = length(namez5b))

produc5b <- nameofproduct5b[[1]] 
produc5b <- rep(produc5b, length.out = length(namez5b))

cater5b <- category5b[[5]] 
ca5b <- rep(cater5b, length.out = length(namez5b))

ratingz5b <- ratings5b[[1]]
if (length(ratingz5b) > length(namez5b)) {
    ratingz5b <- tail(ratingz5b, length(namez5b)) 
} else if (length(ratingz5b) < length(namez5b)) {
    ratingz5b <- c(ratingz5b, rep(NA, length(namez5b) - length(ratingz5b)))
}

```

```{r}
max_length <- max(
  length(ca5b),
  length(producto5b),
  length(produc5b),
  length(namez5b),
  length(ratingz5b),
  length(dates5b[[1]]),
  length(title5b[[1]]),
  length(text5b[[1]])
)

ca5b <- c(ca5b, rep(NA, max_length - length(ca5b)))
producto5b <- c(producto5b, rep(NA, max_length - length(producto5b)))
produc5b <- c(produc5b, rep(NA, max_length - length(produc5b)))
namez5b <- c(namez5b, rep(NA, max_length - length(namez5b)))
ratingz5b <- c(ratingz5b, rep(NA, max_length - length(ratingz5b)))
dates5b[[1]] <- c(dates5b[[1]], rep(NA, max_length - length(dates5b[[1]])))
title5b[[1]] <- c(title5b[[1]], rep(NA, max_length - length(title5b[[1]])))
text5b[[1]] <- c(text5b[[1]], rep(NA, max_length - length(text5b[[1]])))

pencil6 <- data.frame(Category = ca5b,
                     Product_number = producto5b,
                      Name_of_Product = produc5b,
                      Userame = namez5b,
                       Rating = ratingz5b,
                       Date = dates5b[[1]],
                       Title_of_Review = title5b[[1]],
                       Text_of_Review = text5b[[1]],
                       stringsAsFactors = FALSE
                       )
head(pencil6, 50)
pencil6 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama5b2 <- names5b[[2]]
namez5b2 <- nama5b2[!grepl("What did I use this assortment of pencils for?", nama5b2, ignore.case = TRUE)]
namez5b2 <- unique(namez5b2)
namez5b2 <- namez5b2[-2] 

producto5b2 <- productnumber5b[[2]] 
producto5b2 <- rep(producto5b2, length.out = length(namez5b2))

produc5b2 <- nameofproduct5b[[2]] 
produc5b2 <- rep(produc5b2, length.out = length(namez5b2))


cater5b2 <- category5b[[5]]
ca5b2 <- rep(cater5b2, length.out = length(namez5b2))


ratingz5b2 <- ratings5b[[2]]
if (length(ratingz5b2) > length(namez5b2)) {
    ratingz5b2 <- tail(ratingz5b2, length(namez5b2)) 
} else if (length(ratingz5b2) < length(namez5b2)) {
    ratingz5b2 <- c(ratingz5b2, rep(NA, length(namez5b2) - length(ratingz5b2)))
}
```
```{r}
max_length <- max(
  length(ca5b2),
  length(producto5b2),
  length(produc5b2),
  length(namez5b2),
  length(ratingz5b2),
  length(dates5b[[2]]),
  length(title5b[[2]]),
  length(text5b[[2]])
)

ca5b2 <- c(ca5b2, rep(NA, max_length - length(ca5b2)))
producto5b2 <- c(producto5b2, rep(NA, max_length - length(producto5b2)))
produc5b2 <- c(produc5b2, rep(NA, max_length - length(produc5b2)))
namez5b2 <- c(namez5b2, rep(NA, max_length - length(namez5b2)))
ratingz5b2 <- c(ratingz5b2, rep(NA, max_length - length(ratingz5b2)))
dates5b[[2]] <- c(dates5b[[2]], rep(NA, max_length - length(dates5b[[2]])))
title5b[[2]] <- c(title5b[[2]], rep(NA, max_length - length(title5b[[2]])))
text5b[[2]] <- c(text5b[[2]], rep(NA, max_length - length(text5b[[2]])))

pencil7 <- data.frame(Category = ca5b2,
                     Product_number = producto5b2,
                      Name_of_Product = produc5b2,
                      Userame = namez5b2,
                       Rating = ratingz5b2,
                       Date = dates5b[[2]],
                       Title_of_Review = title5b[[2]],
                       Text_of_Review = text5b[[2]],
                       stringsAsFactors = FALSE
                       )
head(pencil7, 50)
pencil7 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama5b3 <- names5b[[3]]
namez5b3 <- nama5b3[!grepl("NEW Mechanical Pencil Video", nama5b3, ignore.case = TRUE)]
namez5b3 <- namez5b3[-(1:2)]
namez5b3 <- unique(namez5b3)
producto5b3 <- productnumber5b[[3]]
producto5b3 <- rep(producto5b3, length.out = length(namez5b3))
produc5b3 <- nameofproduct5b[[3]]
produc5b3 <- rep(produc5b3, length.out = length(namez5b3))
cater5b3 <- category5b[[5]]
ca5b3 <- rep(cater5b3, length.out = length(namez5b3))
ratingz5b3 <- ratings5b[[3]]
if (length(ratingz5b3) > length(namez5b3)) {
    ratingz5b3 <- tail(ratingz5b3, length(namez5b3)) 
} else if (length(ratingz5b3) < length(namez5b3)) {
    ratingz5b3 <- c(ratingz5b3, rep(NA, length(namez5b3) - length(ratingz5b3)))
}
```
```{r}
max_length <- max(
  length(ca5b3),
  length(producto5b3),
  length(produc5b3),
  length(namez5b3),
  length(ratingz5b3),
  length(dates5b[[3]]),
  length(title5b[[3]]),
  length(text5b[[3]])
)

ca5b3 <- c(ca5b3, rep(NA, max_length - length(ca5b3)))
producto5b3 <- c(producto5b3, rep(NA, max_length - length(producto5b3)))
produc5b3 <- c(produc5b3, rep(NA, max_length - length(produc5b3)))
namez5b3 <- c(namez5b3, rep(NA, max_length - length(namez5b3)))
ratingz5b3 <- c(ratingz5b3, rep(NA, max_length - length(ratingz5b3)))
dates5b[[3]] <- c(dates5b[[3]], rep(NA, max_length - length(dates5b[[3]])))
title5b[[3]] <- c(title5b[[3]], rep(NA, max_length - length(title5b[[3]])))
text5b[[3]] <- c(text5b[[3]], rep(NA, max_length - length(text5b[[3]])))

pencil8 <- data.frame(Category = ca5b3,
                     Product_number = producto5b3,
                      Name_of_Product = produc5b3,
                      Userame = namez5b3,
                       Rating = ratingz5b3,
                       Date = dates5b[[3]],
                       Title_of_Review = title5b[[3]],
                       Text_of_Review = text5b[[3]],
                       stringsAsFactors = FALSE
                       )
head(pencil8, 50)
pencil8 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama5b4 <- names5b[[4]]
namez5b4 <- nama5b4[!grepl("Crayola Suncatcher Craft", nama5b4, ignore.case = TRUE)]
namez5b4 <- namez5b4[-(1:2)]
namez5b4 <- unique(namez5b4)
producto5b4 <- productnumber5[[4]]
producto5b4 <- rep("Product 9", length.out = length(namez5b4))  # Ensures Product 9
produc5b4 <- nameofproduct5b[[4]]
produc5b4 <- rep(produc5b4, length.out = length(namez5b4))
cater5b4 <- category5[[5]]  # Ensures Category 5
ca5b4 <- rep(cater5b4, length.out = length(namez5b4))
ratingz5b4 <- ratings5b[[4]]
if (length(ratingz5b4) > length(namez5b4)) {
    ratingz5b4 <- tail(ratingz5b4, length(namez5b4)) 
} else if (length(ratingz5b4) < length(namez5b4)) {
    ratingz5b4 <- c(ratingz5b4, rep(NA, length(namez5b4) - length(ratingz5b4)))
}

```
```{r}
max_length <- max(
  length(ca5b4),
  length(producto5b4),
  length(produc5b4),
  length(namez5b4),
  length(ratingz5b4),
  length(dates5b[[4]]),
  length(title5b[[4]]),
  length(text5b[[4]])
)

ca5b4 <- c(ca5b4, rep(NA, max_length - length(ca5b4)))
producto5b4 <- c(producto5b4, rep(NA, max_length - length(producto5b4)))
produc5b4 <- c(produc5b4, rep(NA, max_length - length(produc5b4)))
namez5b4 <- c(namez5b4, rep(NA, max_length - length(namez5b4)))
ratingz5b4 <- c(ratingz5b4, rep(NA, max_length - length(ratingz5b4)))
dates5b[[4]] <- c(dates5b[[4]], rep(NA, max_length - length(dates5b[[4]])))
title5b[[4]] <- c(title5b[[4]], rep(NA, max_length - length(title5b[[4]])))
text5b[[4]] <- c(text5b[[4]], rep(NA, max_length - length(text5b[[4]])))


pencil9 <- data.frame(Category = ca5b4,
                     Product_number = producto5b4,
                      Name_of_Product = produc5b4,
                      Userame = namez5b4,
                       Rating = ratingz5b4,
                       Date = dates5b[[4]],
                       Title_of_Review = title5b[[4]],
                       Text_of_Review = text5b[[4]],
                       stringsAsFactors = FALSE
                       )
head(pencil9, 50)
pencil9 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama5b5 <- names5b[[5]]
namez5b5 <- nama5b5[!grepl("Power of the Pencil", nama5b5, ignore.case = TRUE)]
namez5b5 <- namez5b5[-(1:2)]
namez5b5 <- unique(namez5b5)
producto5b5 <- productnumber5[[5]]
producto5b5 <- rep("Product 10", length.out = length(namez5b5))  
produc5b5 <- nameofproduct5b[[5]]
produc5b5 <- rep(produc5b5, length.out = length(namez5b5))
cater5b5 <- category5[[5]] 
ca5b5 <- rep(cater5b5, length.out = length(namez5b5))
ratingz5b5 <- ratings5b[[5]]
if (length(ratingz5b5) > length(namez5b5)) {
    ratingz5b5 <- tail(ratingz5b5, length(namez5b5)) 
} else if (length(ratingz5b5) < length(namez5b5)) {
    ratingz5b5 <- c(ratingz5b5, rep(NA, length(namez5b5) - length(ratingz5b5)))
}
```
```{r}
max_length <- max(
  length(ca5b5),
  length(producto5b5),
  length(produc5b5),
  length(namez5b5),
  length(ratingz5b5),
  length(dates5b[[5]]),
  length(title5b[[5]]),
  length(text5b[[5]])
)

ca5b5 <- c(ca5b5, rep(NA, max_length - length(ca5b5)))
producto5b5 <- c(producto5b5, rep(NA, max_length - length(producto5b5)))
produc5b5 <- c(produc5b5, rep(NA, max_length - length(produc5b5)))
namez5b5 <- c(namez5b5, rep(NA, max_length - length(namez5b5)))
ratingz5b5 <- c(ratingz5b5, rep(NA, max_length - length(ratingz5b5)))
dates5b[[5]] <- c(dates5b[[5]], rep(NA, max_length - length(dates5b[[5]])))
title5b[[5]] <- c(title5b[[5]], rep(NA, max_length - length(title5b[[5]])))
text5b[[5]] <- c(text5b[[5]], rep(NA, max_length - length(text5b[[5]])))

pencil10 <- data.frame(Category = ca5b5,
                     Product_number = producto5b5,
                      Name_of_Product = produc5b5,
                      Userame = namez5b5,
                       Rating = ratingz5b5,
                       Date = dates5b[[5]],
                       Title_of_Review = title5b[[5]],
                       Text_of_Review = text5b[[5]],
                       stringsAsFactors = FALSE
                       )
head(pencil10, 50)
pencil10 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```