---
title: "Amazon_second_category_CANVAS#group_(Mijares_Mabalina_Compay)"
author: "Mijares_Compay_Mabalina"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(polite)
library(kableExtra)
library(rmarkdown)
library(httr)
library(rvest)
library(dplyr)
library(stringr)
library(ggplot2)
```
CANVAS
```{r}
urls2 <- c('https://www.amazon.com/ESRICH-Stretched-Canvases-60-Acid-Free/dp/B0CY2MNQP4/ref=sr_1_5?crid=3970M5SNPP4R6&dib=eyJ2IjoiMSJ9.6he99om3x7OhZQmMoJwzLphHFKMpz3ImBRyrHD0e-xcMbg-aMzeGb9KOJ6GRvQWdDAza5yW20BBlBbN2Ficd0sj7E4On8Fq650z_qcfEPnocFu8BsRKE9WvGzmAXnE1pA2xCVJbSLRf9Sh0pFmVwsO6t9GMMebEmQZ4Wgfz7McWZAZ6_In-n3mS4TtndVYLMSumw7Z8p0KFz6c93QWYHTXobbnxgEy0Wa_Ol0iznG_2_Mq6mc76EpgfJGD2vtAk1vjr858Gl6C_PkLA_p3z3-dMLmkuDboScQHqB7GPTdts.APC6uAhWTbe0atOKefqqrzIMnyLr_R7ZFtp-5veWFwU&dib_tag=se&keywords=ESRICH+Stretched+Canvases+for+Painting+8x10%2C+60+Pack+8x10+Canvases+for+Painting%2CPrimed+Acid-Free+Cotton+Blank+Canvas%2C+Paint+Canvases&qid=1733810397&sprefix=esrich+stretched+canvases+for+painting+8x10%2C+60+pack+8x10+canvases+for+painting%2Cprimed+acid-free+cotton+blank+canvas%2C+paint+canvases+%2Caps%2C622&sr=8-5',
           'https://www.amazon.com/Madisi-Painting-Canvas-Panels-Classroom/dp/B07SGQ7VG7/ref=sr_1_5?crid=1P7U6LX547HCS&dib=eyJ2IjoiMSJ9.MtLA381GKevTPqGpSEhKx5rp5EgsVbbpjQbu2m8KFpj8xl0Z-qc__4dYK8RD_4zeXPnMqrMjHqelsiQgBf_9nN7sOKHWIpfrlF7Qs_mFQ8NvEsP44xyK2eRXa8-y_02SCUuZcmjuME080s3c7kftU38lkr3HJ5DaiYKP9_uxR4sHE-FJXkdDocAAIHih96LbODry62Z4kGxlda9wDZ1w0ShiHjzOg67YRJmyNappmCI1uKEOpPo2evrfUJA1ecD8AH3r8kJC_SPsp-Rxd2EmUirPFPcZaYXiZyPeYJ3hTVc.hqiLhyJ2kNR3hGrwbhT42x2pzQX8Ki3pdNkQDqJ8AZE&dib_tag=se&keywords=madisi+painting+canvas+panels+72+pack%2C+5x7%2C+classroom&qid=1733810444&sprefix=madisi+painting+canvas+panels+72+pack%2C+5x7%2C+classroo%2Caps%2C312&sr=8-5',
           'https://www.amazon.com/KEFF-Stretched-Canvas-Painting-Blank/dp/B0DJV41SRW/ref=sr_1_5?crid=3PG8VF05EDRY9&dib=eyJ2IjoiMSJ9.iXPynsApOkvJWc1U84heDoX_782-upfzraRe5n1VLFm5obF2xeF__5hdSYBCfZAES6vGNb2MIXh2rN9st6W3r8FoRYAgwzFyIsYAqoB9R5XrBHjjnU24at-X2nCx590GRqmto_y7SfPNKZO2rKJRCG5zbkjn1b6os087T4vVdyHCkWghEtGpK-bX1rick7S4RjQemI8-1jdepNSs8YZftQcT_tciYTQaqMCLSaDpODMxYNvtQUZAbzv_H_yQLYBi2BJcWTaptedMfOaV0_95D7hbNQYlr1qNC-n_JMMoc-E.redJbuZvyr9_owN2p28lIaDWjuHTNjuid2og7-FeZhI&dib_tag=se&keywords=KEFF+Stretched+Canvas+for+Painting+%2810+Pack%29+Blank+Pain&qid=1733810468&sprefix=keff+stretched+canvas+for+painting+10+pack+blank+pain%2Caps%2C319&sr=8-5',
           'https://www.amazon.com/Canvases-Painting-Painting-Acid-Free-Watercolor/dp/B0BJZXQ88M/ref=sr_1_5?crid=1XRQ2ZND0379B&dib=eyJ2IjoiMSJ9.Hz3GCPZswVMxZAoUELrQcrAVMo6y1MDPSHVNDw69xCBR1Ufo_9rPNSJWbtcWUNAUEqxymf0PUtHMVP9Tm6lRQw-VVCYG1nlHMn0mp3CBi42nEovcpaZry0vLXzOoGw2aUfzFpuZOMs_5TW-pL73F95y5WD8MfkiU9c6biEFMIoFyLwVHcrnSJh9gO3nD1mq8Q0fJzvXeJQuU4Gxuqdr4Y4fE1hQIbeF2HV5DdX4NNaFeGZjLgUIHZY2iTzaYmu-2cWQcSrxuvYWWpcEy2tsY3RfSriHXqWgIRgo0yWcYfKQ.85M207IkFuzt9__1jDxw6Qu7-ORpC5LNt2eLpTlb6lo&dib_tag=se&keywords=simetufy+72+pack+canvas+boards+for+painting+5+x+7+inch&qid=1733810515&sprefix=simetufy+72+pack+canvas+boards+for+painting+5+x+7+inc%2Caps%2C330&sr=8-5',
           'https://www.amazon.com/KEFF-KA27055-Canvas-Boards-Pack/dp/B085F4JH1H/ref=sr_1_5?crid=1BY771N0AXLG2&dib=eyJ2IjoiMSJ9.rQWQldAB_5qR7vJYqWA-SXJU3UQ8cY9tPGflxqqdspbkYm3DXux7oWm8m5e--9lW3QfcyU7FobpHYU7_Z39jax-H8lpUnBSYzIsXx2SHTJwispU8r4Ku1-Rug3NIvbxZqEw7ghMdnORtjVDRi9NsJHuxWzm7VYb51xbWT7Q7h59LkjUaY4RQ6eVSeINiXvQ-qfKH5fd8L2_ZjXQZ3lv_zJr0t3uHqVN9JicPjg0DqTaGBX4qeigfIacv92ePWLBcXVc6DgUmb_LsyMmo7zudOx7gvwvk4g2Uw1YcArl2zpA.sXuRT_FIbYCJ65ZLHzlm0cjwAN_wQJG97s4sx71dbOY&dib_tag=se&keywords=KEFF+24-Pack+Bulk+Canvas+for+Painting%2C+6+of+5x7%2C+8x10%2C&qid=1733810557&sprefix=keff+24-pack+bulk+canvas+for+painting%2C+6+of+5x7%2C+8x10%2C+%2Caps%2C328&sr=8-5'
           ,'https://www.amazon.com/Acid-Free-Canvases-Painting-Acrylics-Watercolor/dp/B09637DLSL/ref=sr_1_5?crid=9UPXLL8IWCUY&dib=eyJ2IjoiMSJ9.DLyui9YtglumHJHleCgE4HY5vRqW2hWnq5VOfFHnU0jgNBz_K8mtl4w2Z-kkfVwTrvrPovQgtwS58OHY-xX3m3-QzStOOhDKNo_9tJcQwYWPSSBBtCQdp2ox-eLnwbR4G8xTY6fQyy6CDlTo8vCq1hVhuysnrJHIJsCi11GrreKM157vgdeHdYjP0_N49QjQE39_BEUc11YdUktDX3VenVfUaOAie4k52yV1P3fD4_2YYtWR5t1iLo-oB-z7N-FR0RxvJeXEU-DanqwK-SEVOHzmdiLIwOQPI8FCS7zEAqU.bVbrFplpfFqDX1zdqfESBBMFWjs3nG4BcY8hgkMoKa4&dib_tag=se&keywords=Artkey+Canvases+for+Painting+8x10+Inch+12-Pack%2C+10+oz+Primed+100%25+Cotton+White+Blank+Canvas+Boards+for+Painting%2C+Art+Supplies+Paint+Canvas+Panels+for+Acrylic+Oil+Watercolor+Tempera+Paints&qid=1733810589&sprefix=keff+24-pack+bulk+canvas+for+painting%2C+6+of+5x7%2C+8x10%2C%2Caps%2C439&sr=8-5',
           'https://www.amazon.com/GOTIDEAL-Canvas-Professional-Painting-Acrylic/dp/B087LY7S1F/ref=sr_1_5?crid=2AQ2NX1Y0X7Y4&dib=eyJ2IjoiMSJ9.n4G6JRJ9GL6EYV8mdPvt4HQMgjh_GzNxMLbZJZpsUpja8CPTkW1AkmHYCILbiUsd7q04aQqq8YYf4szE4LGmr58-RBRz6PGmfjoEhXzbaT7HLK50GoFl3VrgUuU2JRsMNFkTSZ99vNu2Wpvvk0YIyZI0rP00bJW94pBlVuVXv8QTjkj4DY_6oNmWLtdVqWmqqNNmnGstipNiFyBamuRsKJ4GtCjQcOQSgl-xSOy4UpTZNoHxMLY-QVkEkuxKd9n-WCMfTBBvEokokKHjVnNSMzW4g9-Ne171zLTm4xCZWKM.LKKH8y9abstkpztKhmiufZOMlPATelXLz28rhYQANGw&dib_tag=se&keywords=GOTIDEAL+Stretched+Canvas%2C+Multi+Pack+4x4%2C+5x7%2C+8x10%2C9x12%2C+11x14+Set+of+10%2C+Primed+White+-+100%25+Cotton+Artist+Canvas+Boards+for+Painting%2C+Acrylic+Pouring%2C+Oil+Paint+Dry+%26+Wet+Art+Media&qid=1733810611&sprefix=gotideal+stretched+canvas%2C+multi+pack+4x4%2C+5x7%2C+8x10%2C9x12%2C+11x14+set+of+10%2C+primed+white+-+100%25+cotton+artist+canvas+boards+for+painting%2C+acrylic+pouring%2C+oil+paint+dry+%26+wet+art+media+%2Caps%2C373&sr=8-5',
           'https://www.amazon.com/Superise-Canvases-Painting-Painting-Acrylic/dp/B087F4F5DK/ref=sr_1_5?crid=BVBJGZ04X9O1&dib=eyJ2IjoiMSJ9.fDLQPmAL-n7N7o9l2UYvnkqB73mo9ADocP7UN8bMR1EPr7EcAPhBf3v4wVnPN6MN2tym-_Eer5QJqoVGJbGS-9O8CD1kYanTOArMh9Psd9sFDXyFMRyO8UdU3obpqPEsiRa15ZIvush5uuU_YomiGuSzRYQ_m5liA5_deg4CAzUE3i58PauwDfuIRpvlq4zkPSRUR-lIzAAs03NI73ZMMltiCDh8hiGm95wcIpqK_lYPHbgebpTSU0VkhOHJSxKUFJHvQM1gRAGz_PiHqxo9H08WHOQ4f6fdt0tFqH_Gbnk.lqZiddm3ZU4gzS46S608X4Ktlv_Rk7vhgD6kocIphA8&dib_tag=se&keywords=Simetufy+11+x+14+Inch+Canvas+Boards+for+Painting+32+Pack%2C+Pre-Primed+Blank+Canvases+for+Painting+100%25+Cotton+Paint+Canvas+for+Acrylic%2C+O&qid=1733810678&sprefix=simetufy+11+x+14+inch+canvas+boards+for+painting+32+pack%2C+pre-primed+blank+canvases+for+painting+100%25+cotton+paint+canvas+for+acrylic%2C+o%2Caps%2C304&sr=8-5',
           'https://www.amazon.com/Shuttle-Art-Painting-Canvas-Acrylic/dp/B08JLNHTW3/ref=sr_1_1?crid=YPBK23ZCT22T&dib=eyJ2IjoiMSJ9.65sSFcIHGxnubg_qAzpeVsd7Qog5iW_19lXIyJIuash-fX7ivKf8voJ3jgwHNA4cr7u3Kwu1VoiplLU88uvnmjfVlcOZtIs-G6-e0Puj2ups7NK45_Ek21YgwrYjC1Je4xTaA3Dia9pfJsJbUFOq03yUjMBIuG392GUyHhHi1GSyOOStD8qrhsnH-43AQfrEQoJ3NVoGBO0FWVhTA53eLgzuQvJcW-jNChvvbkguerIX3iBEsChW2F31Thtq3bjCh_OLnF1lRbqToF_tRN8MgWSkRHarBR_Hk8D7nlXz_jM.PM-gVGVYmqBbOJTevATz9bDChM-hBgXXH9naAOf5yxQ&dib_tag=se&keywords=Shuttle+Art+Painting+Canvas+Panel%2C+52+Multi+Pack%2C+5x5%2C+6x6%2C+8x8%2C+10x10+inch+%2813+PCS+of+Each%29%2C+100%25+Cotton+Art+Canvas+Board+Primed+White%2C+Blank+Canvas+for+Kids+Adults+for+Acrylic+Oil+Painting&qid=1733810714&sprefix=shuttle+art+painting+canvas+panel%2C+52+multi+pack%2C+5x5%2C+6x6%2C+8x8%2C+10x10+inch+13+pcs+of+each+%2C+100%25+cotton+art+canvas+board+primed+white%2C+blank+canvas+for+kids+adults+for+acrylic+oil+painting+%2Caps%2C354&sr=8-1',
           'https://www.amazon.com/Canvases-Painting-Shuttle-Art-Stretched/dp/B08XYYRCMP/ref=sr_1_1?crid=1QJQ74FFDJX4J&dib=eyJ2IjoiMSJ9.CRLCKyFEfbP_seFrct5eu2EuT_JdjSE5liGQGvaEEKQHMgiKBrYHQY6rydWEEDSh99mR83VAtS9SIFkAhuFmyD0wNSmiRZC4oOi4TfADOpQ3TTtzWlRIk7OLiSvtKQrOf_P_8icgjaF-3VhTgt5wwB9-TzHL3yi1sbWenYufmw1qenBtFYK4P9KhC1T7mqjPZoXMibtULrKoJl_5pA8td-2kCzI1l4xgzXsfdRtKjMNjYhP6ZcwZUTAu_BdkKMrRhYQ3PuP7U3jQ0QqbOyO5m1V_7YXMSIA8iBzrFQZbAP0.ZztHQQLi6_Ox2CvoroRb9ShjtqJ8v6VNqnDQVCQXiUs&dib_tag=se&keywords=Canvases+for+Painting%2C+Shuttle+Art+34+Pack+Multi+Sizes+Stretched+Canvas+and+Canvas+Panels%2C+5x7%E2%80%9D%2C+8x10%E2%80%9D%2C+9x12%E2%80%9D%2C+11x14%E2%80%9D%2C+100%25+Cotton+Primed+Canvas+Boards+for+Painting%2C+Blank+Canvas+for+Acrylic+Oil+Paint&qid=1733810745&sprefix=canvases+for+painting%2C+shuttle+art+34+pack+multi+sizes+stretched+canvas+and+canvas+panels%2C+5x7+%2C+8x10+%2C+9x12+%2C+11x14+%2C+100%25+cotton+primed+canvas+boards+for+painting%2C+blank+canvas+for+acrylic+oil+paint+%2Caps%2C323&sr=8-1')

nameofproduct2 <- vector("list", length(urls2))
names2 <- vector("list", length(urls2))
ratings2 <- vector("list", length(urls2))
dates2 <- vector("list", length(urls2))
title2 <- vector("list", length(urls2))
text2 <- vector("list", length(urls2))
n2 <- vector("list", length(urls2))
```

```{r}
df <- list()

for (i in seq_along(urls2)) {
    session <- bow(urls2[i], user_agent = "Educational")
    webpage2 <- scrape(session)
  
    
    nam2 <- webpage2 %>% html_nodes(".a-profile-name") %>% html_text()
    nam2 <- nam2[!grepl("hair care routine for BROKEN DAMAGED hair|Amazon Customer", nam2, ignore.case = TRUE)]
    nam2 <- nam2[nam2 != ""]
    n2[[i]] <- nam2
    name2 <- c() 
    non_amazon_seen2 <- FALSE  
    for (na2 in nam2) {
      if (na2 == "Amazon Customer") {

        if (non_amazon_seen2) {
          name2 <- c(name2, na2)
        }
      } else {
        name2 <- c(name2, na2)
        non_amazon_seen2 <- TRUE
        }
    }
    name2 <- name2[!duplicated(name2) | name2 == "Amazon Customer"]
    names2[[i]] <- name2
    
        nameofproduct2[[i]] <-  webpage2 %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct2[[i]] <- rep(nameofproduct2[[i]], length.out = length(names2[[i]]))
    
    rate2 <- webpage2 %>% html_nodes(".a-icon-alt") %>% html_text()
    rati2 <- rate2[!grepl("Previous page of related Sponsored Products|Next page of related Sponsored Products|Previous page|Next page", rate2, ignore.case = TRUE)]
    rat2 <- gsub(" out of 5 stars", "", rati2)
    rats2 <- rat2
    if (length(rats2) > length(name2)) {
    rats2 <- tail(rats2, length(name2)) 
    } else if (length(rats2) < length(name2)) {
    rats2 <- c(rats2, rep(NA, length(name2) - length(rats2)))
    }

    ratings2[[i]] <- rats2
    
    dat2 <- webpage2 %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date2 <- gsub("Reviewed.*on ", "", dat2)
    dates2[[i]] <- date2

    titl2 <- webpage2 %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit2 <- gsub("Reviewed.*on ", "", titl2)
    ti2 <- gsub(".*stars\\s*", "", tit2)
    t2 <- gsub("\\s+", " ", ti2)
    title2[[i]] <- t2

    tex2 <- webpage2 %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te2 <- gsub("\\n", " ", tex2)
    t2 <- gsub("\\s+", " ", te2)
    text2[[i]] <- trimws(t2)
}
    
```

```{r}
cate2 <- c("Category 1: BRUSH", "Category 2: CANVAS", "Category 3", "Category 4", "Category 5")
category2 <- vector("list", length(cate2))
for (i in seq_along(cate2)) {
    category2[[i]] <- cate2[i]
}
```


```{r}
for (i in seq_along(cate2)) {
    category2[[i]] <- rep(category2[[i]], length.out = length(names2[[i]]))
}
```

```{r}
productnumbe2 <- c("Product 1", "Product 2", "Product 3", "Product 4", "Product 5", "Product 6", "Product 7", "Product 8", "Product 9", "Product 10")
productnumber2 <- vector("list", length(productnumbe2))
for (i in seq_along(productnumbe2)) {
    productnumber2[[i]] <- productnumbe2[i]
}
for (i in seq_along(urls2)) {
    productnumber2[[i]] <- rep(productnumber2[[i]], length.out = length(names2[[i]]))
}
```

```{r}
urls2b <- c('https://www.amazon.com/GOTIDEAL-Canvas-Professional-Painting-Acrylic/dp/B087LY7S1F/ref=sr_1_5?crid=2AQ2NX1Y0X7Y4&dib=eyJ2IjoiMSJ9.n4G6JRJ9GL6EYV8mdPvt4HQMgjh_GzNxMLbZJZpsUpja8CPTkW1AkmHYCILbiUsd7q04aQqq8YYf4szE4LGmr58-RBRz6PGmfjoEhXzbaT7HLK50GoFl3VrgUuU2JRsMNFkTSZ99vNu2Wpvvk0YIyZI0rP00bJW94pBlVuVXv8QTjkj4DY_6oNmWLtdVqWmqqNNmnGstipNiFyBamuRsKJ4GtCjQcOQSgl-xSOy4UpTZNoHxMLY-QVkEkuxKd9n-WCMfTBBvEokokKHjVnNSMzW4g9-Ne171zLTm4xCZWKM.LKKH8y9abstkpztKhmiufZOMlPATelXLz28rhYQANGw&dib_tag=se&keywords=GOTIDEAL+Stretched+Canvas%2C+Multi+Pack+4x4%2C+5x7%2C+8x10%2C9x12%2C+11x14+Set+of+10%2C+Primed+White+-+100%25+Cotton+Artist+Canvas+Boards+for+Painting%2C+Acrylic+Pouring%2C+Oil+Paint+Dry+%26+Wet+Art+Media&qid=1733810611&sprefix=gotideal+stretched+canvas%2C+multi+pack+4x4%2C+5x7%2C+8x10%2C9x12%2C+11x14+set+of+10%2C+primed+white+-+100%25+cotton+artist+canvas+boards+for+painting%2C+acrylic+pouring%2C+oil+paint+dry+%26+wet+art+media+%2Caps%2C373&sr=8-5',
           'https://www.amazon.com/Superise-Canvases-Painting-Painting-Acrylic/dp/B087F4F5DK/ref=sr_1_5?crid=BVBJGZ04X9O1&dib=eyJ2IjoiMSJ9.fDLQPmAL-n7N7o9l2UYvnkqB73mo9ADocP7UN8bMR1EPr7EcAPhBf3v4wVnPN6MN2tym-_Eer5QJqoVGJbGS-9O8CD1kYanTOArMh9Psd9sFDXyFMRyO8UdU3obpqPEsiRa15ZIvush5uuU_YomiGuSzRYQ_m5liA5_deg4CAzUE3i58PauwDfuIRpvlq4zkPSRUR-lIzAAs03NI73ZMMltiCDh8hiGm95wcIpqK_lYPHbgebpTSU0VkhOHJSxKUFJHvQM1gRAGz_PiHqxo9H08WHOQ4f6fdt0tFqH_Gbnk.lqZiddm3ZU4gzS46S608X4Ktlv_Rk7vhgD6kocIphA8&dib_tag=se&keywords=Simetufy+11+x+14+Inch+Canvas+Boards+for+Painting+32+Pack%2C+Pre-Primed+Blank+Canvases+for+Painting+100%25+Cotton+Paint+Canvas+for+Acrylic%2C+O&qid=1733810678&sprefix=simetufy+11+x+14+inch+canvas+boards+for+painting+32+pack%2C+pre-primed+blank+canvases+for+painting+100%25+cotton+paint+canvas+for+acrylic%2C+o%2Caps%2C304&sr=8-5',
           'https://www.amazon.com/Shuttle-Art-Painting-Canvas-Acrylic/dp/B08JLNHTW3/ref=sr_1_1?crid=YPBK23ZCT22T&dib=eyJ2IjoiMSJ9.65sSFcIHGxnubg_qAzpeVsd7Qog5iW_19lXIyJIuash-fX7ivKf8voJ3jgwHNA4cr7u3Kwu1VoiplLU88uvnmjfVlcOZtIs-G6-e0Puj2ups7NK45_Ek21YgwrYjC1Je4xTaA3Dia9pfJsJbUFOq03yUjMBIuG392GUyHhHi1GSyOOStD8qrhsnH-43AQfrEQoJ3NVoGBO0FWVhTA53eLgzuQvJcW-jNChvvbkguerIX3iBEsChW2F31Thtq3bjCh_OLnF1lRbqToF_tRN8MgWSkRHarBR_Hk8D7nlXz_jM.PM-gVGVYmqBbOJTevATz9bDChM-hBgXXH9naAOf5yxQ&dib_tag=se&keywords=Shuttle+Art+Painting+Canvas+Panel%2C+52+Multi+Pack%2C+5x5%2C+6x6%2C+8x8%2C+10x10+inch+%2813+PCS+of+Each%29%2C+100%25+Cotton+Art+Canvas+Board+Primed+White%2C+Blank+Canvas+for+Kids+Adults+for+Acrylic+Oil+Painting&qid=1733810714&sprefix=shuttle+art+painting+canvas+panel%2C+52+multi+pack%2C+5x5%2C+6x6%2C+8x8%2C+10x10+inch+13+pcs+of+each+%2C+100%25+cotton+art+canvas+board+primed+white%2C+blank+canvas+for+kids+adults+for+acrylic+oil+painting+%2Caps%2C354&sr=8-1',
           'https://www.amazon.com/Canvases-Painting-Shuttle-Art-Stretched/dp/B08XYYRCMP/ref=sr_1_1?crid=1QJQ74FFDJX4J&dib=eyJ2IjoiMSJ9.CRLCKyFEfbP_seFrct5eu2EuT_JdjSE5liGQGvaEEKQHMgiKBrYHQY6rydWEEDSh99mR83VAtS9SIFkAhuFmyD0wNSmiRZC4oOi4TfADOpQ3TTtzWlRIk7OLiSvtKQrOf_P_8icgjaF-3VhTgt5wwB9-TzHL3yi1sbWenYufmw1qenBtFYK4P9KhC1T7mqjPZoXMibtULrKoJl_5pA8td-2kCzI1l4xgzXsfdRtKjMNjYhP6ZcwZUTAu_BdkKMrRhYQ3PuP7U3jQ0QqbOyO5m1V_7YXMSIA8iBzrFQZbAP0.ZztHQQLi6_Ox2CvoroRb9ShjtqJ8v6VNqnDQVCQXiUs&dib_tag=se&keywords=Canvases+for+Painting%2C+Shuttle+Art+34+Pack+Multi+Sizes+Stretched+Canvas+and+Canvas+Panels%2C+5x7%E2%80%9D%2C+8x10%E2%80%9D%2C+9x12%E2%80%9D%2C+11x14%E2%80%9D%2C+100%25+Cotton+Primed+Canvas+Boards+for+Painting%2C+Blank+Canvas+for+Acrylic+Oil+Paint&qid=1733810745&sprefix=canvases+for+painting%2C+shuttle+art+34+pack+multi+sizes+stretched+canvas+and+canvas+panels%2C+5x7+%2C+8x10+%2C+9x12+%2C+11x14+%2C+100%25+cotton+primed+canvas+boards+for+painting%2C+blank+canvas+for+acrylic+oil+paint+%2Caps%2C323&sr=8-1')
nameofproduct2b <- vector("list", length(urls2b))
names2b <- vector("list", length(urls2b))
ratings2b <- vector("list", length(urls2b))
dates2b <- vector("list", length(urls2b))
title2b <- vector("list", length(urls2b))
text2b <- vector("list", length(urls2b))
n2b <- vector("list", length(urls2b))
```

```{r}
df <- list()

for (i in seq_along(urls2b)) {
    session <- bow(urls2b[i], user_agent = "Educational")
    webpage2b <- scrape(session)
  
    
    nam2b <- webpage2b %>% html_nodes(".a-profile-name") %>% html_text()
    nam2b <- nam2b[!grepl("hair care routine for BROKEN DAMAGED hair|Amazon Customer", nam2b, ignore.case = TRUE)]
    nam2b <- nam2b[nam2b != ""]
    n2b[[i]] <- nam2b
    name2b <- c() 
    non_amazon_seen2b <- FALSE  
    for (na2b in nam2b) {
      if (na2b == "Amazon Customer") {

        if (non_amazon_seen2b) {
          name2b <- c(name2b, na2b)
        }
      } else {
        name2b <- c(name2b, na2b)
        non_amazon_seen2b <- TRUE
        }
    }
    name2b <- name2b[!duplicated(name2b) | name2b == "Amazon Customer"]
    names2b[[i]] <- name2b
    
        nameofproduct2b[[i]] <-  webpage2b %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct2b[[i]] <- rep(nameofproduct2b[[i]], length.out = length(names2b[[i]]))
    
    rate2b <- webpage2b %>% html_nodes(".a-icon-alt") %>% html_text()
    rati2b <- rate2b[!grepl("Previous page of related Sponsored Products|Next page of related Sponsored Products|Previous page|Next page", rate2b, ignore.case = TRUE)]
    rat2b <- gsub(" out of 5 stars", "", rati2b)
    rats2b <- rat2b
    if (length(rats2b) > length(name2b)) {
    rats2b <- tail(rats2b, length(name2b)) 
    } else if (length(rats2b) < length(name2b)) {
    rats2b <- c(rats2b, rep(NA, length(name2b) - length(rats2b)))
    }

    ratings2b[[i]] <- rats2b
    
    dat2b <- webpage2b %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date2b <- gsub("Reviewed.*on ", "", dat2b)
    dates2b[[i]] <- date2b

    titl2b <- webpage2b %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit2b <- gsub("Reviewed.*on ", "", titl2b)
    ti2b <- gsub(".*stars\\s*", "", tit2b)
    t2b <- gsub("\\s+", " ", ti2b)
    title2b[[i]] <- t2b

    tex2b <- webpage2b %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te2b <- gsub("\\n", " ", tex2b)
    t2b <- gsub("\\s+", " ", te2b)
    text2b[[i]] <- trimws(t2b)
}
```

```{r}
cate2b <- c("Category 1: BRUSH", "Category 2: CANVAS", "Category 3:", "Category 4:", "Category 5:")
category2b <- vector("list", length(cate2b))
for (i in seq_along(cate2b)) {
    category2b[[i]] <- cate2b[i]
}
```

```{r}
for (i in seq_along(urls2b)) {
    category2b[[i]] <- rep(category2b[[i]], length.out = length(names2b[[i]]))
}
```

```{r}
productnumbe2b <- c("Product 8", "Product 9", "Product 10")
productnumber2b <- vector("list", length(productnumbe2b))
for (i in seq_along(productnumbe2b)) {
    productnumber2b[[i]] <- productnumbe2b[i]
}
```

```{r}
for (i in seq_along(productnumber2b)) {
    productnumber2b[[i]] <- rep(productnumber2b[[i]], length.out = length(names2b[[i]]))
}
```

```{r}
nama9 <- names2[[1]]
namez9 <- nama9[!grepl("The perfect canvases for a paint class or event.", nama9, ignore.case = TRUE)]
namez9 <- namez9[-(1:2)]
producto9 <- productnumber2[[1]]
producto9 <- rep(producto9, length.out = length(namez9))
produc9 <- nameofproduct2[[1]]
produc9 <- rep(produc9, length.out = length(namez9))
cater9 <- category2[[2]]
ca9 <- rep(cater9, length.out = length(namez9))

ratingz9 <- ratings2[[1]]
    if (length(ratingz9) > length(namez9)) {
    ratingz9 <- tail(ratingz9, length(namez9)) 
    } else if (length(ratingz9) < length(namez9)) {
    ratingz9<- c(ratingz9, rep(NA, length(namez9) - length(ratingz9)))
    }
```

```{r}
max_length <- max(
  length(ca9),
  length(producto9),
  length(produc9),
  length(namez9),
  length(ratingz9),
  length(dates2[[1]]),
  length(title2[[1]]),
  length(text2[[1]])
)


ca9 <- c(ca9, rep(NA, max_length - length(ca9)))
producto9 <- c(producto9, rep(NA, max_length - length(producto9)))
produc9 <- c(produc9, rep(NA, max_length - length(produc9)))
namez9 <- c(namez9, rep(NA, max_length - length(namez9)))
ratingz9 <- c(ratingz9, rep(NA, max_length - length(ratingz9)))
dates2[[1]] <- c(dates2[[1]], rep(NA, max_length - length(dates2[[1]])))
title2[[1]] <- c(title2[[1]], rep(NA, max_length - length(title2[[1]])))
text2[[1]] <- c(text2[[1]], rep(NA, max_length - length(text2[[1]])))

canvas1 <- data.frame(Category = ca9,
                     Product_number = producto9,
                      Name_of_Product = produc9,
                      Userame = namez9,
                       Rating = ratingz9,
                       Date = dates2[[1]],
                       Title_of_Review = title2[[1]],
                       Text_of_Review = text2[[1]],
                       stringsAsFactors = FALSE
                       )
head(canvas1, 50)
canvas1 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama10 <- names2[[2]]
namez10 <- nama10[!grepl("LOVE! Madisi Painting Canvas Panels 72 Pack, 5X7", nama10, ignore.case = TRUE)]
namez10 <- namez10[-(1:2)]
producto10 <- productnumber2[[2]]
producto10 <- rep(producto10, length.out = length(namez10))
produc10 <- nameofproduct2[[2]]
produc10 <- rep(produc10, length.out = length(namez10))
cater10 <- category2[[2]]
ca10 <- rep(cater10, length.out = length(namez10))

ratingz10 <- ratings2[[2]]
    if (length(ratingz10) > length(namez10)) {
    ratingz10 <- tail(ratingz10, length(namez10)) 
    } else if (length(ratingz10) < length(namez10)) {
    ratingz10<- c(ratingz10, rep(NA, length(namez10) - length(ratingz10)))
    }
```

```{r}
max_length <- max(
  length(ca10),
  length(producto10),
  length(produc10),
  length(namez10),
  length(ratingz10),
  length(dates2[[2]]),
  length(title2[[2]]),
  length(text2[[2]])
)

ca10 <- c(ca10, rep(NA, max_length - length(ca10)))
producto10 <- c(producto10, rep(NA, max_length - length(producto10)))
produc10 <- c(produc10, rep(NA, max_length - length(produc10)))
namez10 <- c(namez10, rep(NA, max_length - length(namez10)))
ratingz10 <- c(ratingz10, rep(NA, max_length - length(ratingz10)))
dates2[[2]] <- c(dates2[[2]], rep(NA, max_length - length(dates2[[2]])))
title2[[2]] <- c(title2[[2]], rep(NA, max_length - length(title2[[2]])))
text2[[2]] <- c(text2[[2]], rep(NA, max_length - length(text2[[2]])))

canvas2 <- data.frame(Category = ca10,
                     Product_number = producto10,
                      Name_of_Product = produc10,
                      Userame = namez10,
                       Rating = ratingz10,
                       Date = dates2[[2]],
                       Title_of_Review = title2[[2]],
                       Text_of_Review = text2[[2]],
                       stringsAsFactors = FALSE
                       )
head(canvas2, 50)
canvas2 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama11 <- names2[[3]]
namez11 <- nama11[!grepl("NA", nama11, ignore.case = TRUE)]
namez11 <- namez11[-(1:2)]
producto11 <- productnumber2[[3]]
producto11 <- rep(producto11, length.out = length(namez11))
produc11 <- nameofproduct2[[3]]
produc11 <- rep(produc11, length.out = length(namez11))
cater11 <- category2[[2]]
ca11 <- rep(cater11, length.out = length(namez11))

ratingz11 <- ratings2[[3]]
    if (length(ratingz11) > length(namez11)) {
    ratingz11 <- tail(ratingz11, length(namez11)) 
    } else if (length(ratingz11) < length(namez11)) {
    ratingz11<- c(ratingz11, rep(NA, length(namez11) - length(ratingz11)))
    }
```

```{r}
max_length <- max(
  length(ca11),
  length(producto11),
  length(produc11),
  length(namez11),
  length(ratingz11),
  length(dates2[[3]]),
  length(title2[[3]]),
  length(text2[[3]])
)

ca11 <- c(ca11, rep(NA, max_length - length(ca11)))
producto11 <- c(producto11, rep(NA, max_length - length(producto11)))
produc11 <- c(produc11, rep(NA, max_length - length(produc11)))
namez11 <- c(namez11, rep(NA, max_length - length(namez11)))
ratingz11 <- c(ratingz11, rep(NA, max_length - length(ratingz11)))
dates2[[3]] <- c(dates2[[3]], rep(NA, max_length - length(dates2[[3]])))
title2[[3]] <- c(title2[[3]], rep(NA, max_length - length(title2[[3]])))
text2[[3]] <- c(text2[[3]], rep(NA, max_length - length(text2[[3]])))

canvas3 <- data.frame(Category = ca11,
                     Product_number = producto11,
                      Name_of_Product = produc11,
                      Userame = namez11,
                       Rating = ratingz11,
                       Date = dates2[[3]],
                       Title_of_Review = title2[[3]],
                       Text_of_Review = text2[[3]],
                       stringsAsFactors = FALSE
                       )
head(canvas3, 50)
canvas3 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```
```{r}
nama12 <- names2[[4]]
namez12 <- nama12[!grepl("Simetufy Canvas for Oil & Acrylic Painting, 100% Cotton", nama12, ignore.case = TRUE)]
namez12 <- namez12[-(1:2)]
producto12 <- productnumber2[[4]]
producto12 <- rep(producto12, length.out = length(namez12))
produc12 <- nameofproduct2[[4]]
produc12 <- rep(produc12, length.out = length(namez12))
cater12 <- category2[[2]]
ca12 <- rep(cater12, length.out = length(namez12))

ratingz12 <- ratings2[[4]]
    if (length(ratingz12) > length(namez12)) {
    ratingz12 <- tail(ratingz12, length(namez12)) 
    } else if (length(ratingz12) < length(namez12)) {
    ratingz12<- c(ratingz12, rep(NA, length(namez12) - length(ratingz12)))
    }
```

```{r}
max_length <- max(
  length(ca12),
  length(producto12),
  length(produc12),
  length(namez12),
  length(ratingz12),
  length(dates2[[4]]),
  length(title2[[4]]),
  length(text2[[4]])
)

ca12 <- c(ca12, rep(NA, max_length - length(ca12)))
producto12 <- c(producto12, rep(NA, max_length - length(producto12)))
produc12 <- c(produc12, rep(NA, max_length - length(produc12)))
namez12 <- c(namez12, rep(NA, max_length - length(namez12)))
ratingz12 <- c(ratingz12, rep(NA, max_length - length(ratingz12)))
dates2[[4]] <- c(dates2[[4]], rep(NA, max_length - length(dates2[[4]])))
title2[[4]] <- c(title2[[4]], rep(NA, max_length - length(title2[[4]])))
text2[[4]] <- c(text2[[4]], rep(NA, max_length - length(text2[[4]])))

canvas4 <- data.frame(Category = ca12,
                     Product_number = producto12,
                      Name_of_Product = produc12,
                      Userame = namez12,
                       Rating = ratingz12,
                       Date = dates2[[4]],
                       Title_of_Review = title2[[4]],
                       Text_of_Review = text2[[4]],
                       stringsAsFactors = FALSE
                       )
head(canvas4, 50)
canvas4 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama13 <- names2[[5]]
namez13 <- nama13[!grepl("Paint project must have!", nama13, ignore.case = TRUE)]
namez13 <- namez13[-(1:2)]
producto13 <- productnumber2[[5]]
producto13 <- rep(producto13, length.out = length(namez13))
produc13 <- nameofproduct2[[5]]
produc13 <- rep(produc13, length.out = length(namez13))
cater13 <- category2[[2]]
ca13 <- rep(cater13, length.out = length(namez13))

ratingz13 <- ratings2[[5]]
    if (length(ratingz13) > length(namez13)) {
    ratingz13 <- tail(ratingz13, length(namez13)) 
    } else if (length(ratingz13) < length(namez13)) {
    ratingz13<- c(ratingz13, rep(NA, length(namez13) - length(ratingz13)))
    }
```
```{r}
max_length <- max(
  length(ca13),
  length(producto13),
  length(produc13),
  length(namez13),
  length(ratingz13),
  length(dates2[[5]]),
  length(title2[[5]]),
  length(text2[[5]])
)

ca13 <- c(ca13, rep(NA, max_length - length(ca13)))
producto13 <- c(producto13, rep(NA, max_length - length(producto13)))
produc13 <- c(produc13, rep(NA, max_length - length(produc13)))
namez13 <- c(namez13, rep(NA, max_length - length(namez13)))
ratingz13 <- c(ratingz13, rep(NA, max_length - length(ratingz13)))
dates2[[5]] <- c(dates2[[5]], rep(NA, max_length - length(dates2[[5]])))
title2[[5]] <- c(title2[[5]], rep(NA, max_length - length(title2[[5]])))
text2[[5]] <- c(text2[[5]], rep(NA, max_length - length(text2[[5]])))

canvas5 <- data.frame(Category = ca13,
                     Product_number = producto13,
                      Name_of_Product = produc13,
                      Userame = namez13,
                       Rating = ratingz13,
                       Date = dates2[[5]],
                       Title_of_Review = title2[[5]],
                       Text_of_Review = text2[[5]],
                       stringsAsFactors = FALSE
                       )
head(canvas5, 50)
canvas5 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama14 <- n2[[6]]
namez14 <- nama14[!grepl("Artkey Canvas panel with 100% Cotton Surface", nama14, ignore.case = TRUE)]
namez14 <- namez14[-(1:2)]
namez14 <- unique(namez14)
producto14 <- productnumber2[[6]]
producto14 <- rep(producto14, length.out = length(namez14))
produc14 <- nameofproduct2[[6]]
produc14 <- rep(produc14, length.out = length(namez14))
cater14 <- category2[[2]]
ca14 <- rep(cater14, length.out = length(namez14))

ratingz14 <- ratings2[[6]]
    if (length(ratingz14) > length(namez14)) {
    ratingz14 <- tail(ratingz14, length(namez14)) 
    } else if (length(ratingz14) < length(namez14)) {
    ratingz14 <- c(ratingz14, rep(NA, length(namez14) - length(ratingz14)))
    }
```

```{r}
max_length <- max(
  length(ca14),
  length(producto14),
  length(produc14),
  length(namez14),
  length(ratingz14),
  length(dates2[[6]]),
  length(title2[[6]]),
  length(text2[[6]])
)

ca14 <- c(ca14, rep(NA, max_length - length(ca14)))
producto14 <- c(producto14, rep(NA, max_length - length(producto14)))
produc14 <- c(produc14, rep(NA, max_length - length(produc14)))
namez14 <- c(namez14, rep(NA, max_length - length(namez14)))
ratingz14 <- c(ratingz14, rep(NA, max_length - length(ratingz14)))
dates2[[6]] <- c(dates2[[6]], rep(NA, max_length - length(dates2[[6]])))
title2[[6]] <- c(title2[[6]], rep(NA, max_length - length(title2[[6]])))
text2[[6]] <- c(text2[[6]], rep(NA, max_length - length(text2[[6]])))

canvas6 <- data.frame(Category = ca14,
                     Product_number = producto14,
                      Name_of_Product = produc14,
                      Userame = namez14,
                       Rating = ratingz14,
                       Date = dates2[[6]],
                       Title_of_Review = title2[[6]],
                       Text_of_Review = text2[[6]],
                       stringsAsFactors = FALSE
                       )
head(canvas6, 50)
canvas6 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama15 <- names2[[7]]
namez15 <- nama15[!grepl("NA", nama15, ignore.case = TRUE)]
namez15 <- namez15[-(1:2)]
producto15 <- productnumber2[[7]]
producto15 <- rep(producto15, length.out = length(namez15))
produc15 <- nameofproduct2[[7]]
produc15 <- rep(produc15, length.out = length(namez15))
cater15 <- category2[[2]]
ca15 <- rep(cater15, length.out = length(namez15))

ratingz15 <- ratings2[[7]]
    if (length(ratingz15) > length(namez15)) {
    ratingz15 <- tail(ratingz15, length(namez15)) 
    } else if (length(ratingz15) < length(namez15)) {
    ratingz15 <- c(ratingz15, rep(NA, length(namez15) - length(ratingz15)))
    }
```

```{r}
max_length <- max(
  length(ca15),
  length(producto15),
  length(produc15),
  length(namez15),
  length(ratingz15),
  length(dates2[[7]]),
  length(title2[[7]]),
  length(text2[[7]])
)

ca15 <- c(ca15, rep(NA, max_length - length(ca15)))
producto15 <- c(producto15, rep(NA, max_length - length(producto15)))
produc15 <- c(produc15, rep(NA, max_length - length(produc15)))
namez15 <- c(namez15, rep(NA, max_length - length(namez15)))
ratingz15 <- c(ratingz15, rep(NA, max_length - length(ratingz15)))
dates2[[7]] <- c(dates2[[7]], rep(NA, max_length - length(dates2[[7]])))
title2[[7]] <- c(title2[[7]], rep(NA, max_length - length(title2[[7]])))
text2[[7]] <- c(text2[[7]], rep(NA, max_length - length(text2[[7]])))

canvas7 <- data.frame(Category = ca15,
                     Product_number = producto15,
                      Name_of_Product = produc15,
                      Userame = namez15,
                       Rating = ratingz15,
                       Date = dates2[[7]],
                       Title_of_Review = title2[[7]],
                       Text_of_Review = text2[[7]],
                       stringsAsFactors = FALSE
                       )
head(canvas7, 50)
canvas7 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama16 <- names2b[[1]]
namez16 <- nama16[!grepl("NA", nama16, ignore.case = TRUE)]
namez16 <- namez16[-(1:2)]
producto16 <- productnumber2b[[1]]
producto16 <- rep(producto16, length.out = length(namez16))
produc16 <- nameofproduct2b[[1]]
produc16 <- rep(produc16, length.out = length(namez16))
cater16 <- category2b[[2]]
ca16 <- rep(cater16, length.out = length(namez16))

ratingz16 <- ratings2b[[1]]
    if (length(ratingz16) > length(namez16)) {
    ratingz16 <- tail(ratingz16, length(namez16)) 
    } else if (length(ratingz16) < length(namez16)) {
    ratingz16<- c(ratingz16, rep(NA, length(namez16) - length(ratingz16)))
    }
```

```{r}
max_length <- max(
  length(ca16),
  length(producto16),
  length(produc16),
  length(namez16),
  length(ratingz16),
  length(dates2b[[1]]),
  length(title2b[[1]]),
  length(text2b[[1]])
)

ca16 <- c(ca16, rep(NA, max_length - length(ca16)))
producto16 <- c(producto16, rep(NA, max_length - length(producto16)))
produc16 <- c(produc16, rep(NA, max_length - length(produc16)))
namez16 <- c(namez16, rep(NA, max_length - length(namez16)))
ratingz16 <- c(ratingz16, rep(NA, max_length - length(ratingz16)))
dates2b[[1]] <- c(dates2b[[1]], rep(NA, max_length - length(dates2b[[1]])))
title2b[[1]] <- c(title2b[[1]], rep(NA, max_length - length(title2b[[1]])))
text2b[[1]] <- c(text2b[[1]], rep(NA, max_length - length(text2b[[1]])))

canvas8 <- data.frame(Category = ca16,
                     Product_number = producto16,
                      Name_of_Product = produc16,
                      Userame = namez16,
                       Rating = ratingz16,
                       Date = dates2b[[1]],
                       Title_of_Review = title2b[[1]],
                       Text_of_Review = text2b[[1]],
                       stringsAsFactors = FALSE
                       )
head(canvas8, 50)
canvas8 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama17 <- names2b[[2]]
namez17 <- nama17[!grepl("Simetufy Canvas for Oil & Acrylic Painting, 100% Cotton", nama17, ignore.case = TRUE)]
namez17 <- namez17[-(1:2)]
producto17 <- productnumber2b[[2]]
producto17 <- rep(producto17, length.out = length(namez17))
produc17 <- nameofproduct2b[[2]]
produc17 <- rep(produc17, length.out = length(namez17))
cater17 <- category2b[[2]]
ca17 <- rep(cater17, length.out = length(namez17))

ratingz17 <- ratings2b[[1]]
    if (length(ratingz17) > length(namez17)) {
    ratingz17 <- tail(ratingz17, length(namez17)) 
    } else if (length(ratingz17) < length(namez17)) {
    ratingz17<- c(ratingz17, rep(NA, length(namez17) - length(ratingz17)))
    }
```
```{r}
max_length <- max(
  length(ca17),
  length(producto17),
  length(produc17),
  length(namez17),
  length(ratingz17),
  length(dates2b[[2]]),
  length(title2b[[2]]),
  length(text2b[[2]])
)

ca17 <- c(ca17, rep(NA, max_length - length(ca17)))
producto17 <- c(producto17, rep(NA, max_length - length(producto17)))
produc17 <- c(produc17, rep(NA, max_length - length(produc17)))
namez17 <- c(namez17, rep(NA, max_length - length(namez17)))
ratingz17 <- c(ratingz17, rep(NA, max_length - length(ratingz17)))
dates2b[[2]] <- c(dates2b[[2]], rep(NA, max_length - length(dates2b[[2]])))
title2b[[2]] <- c(title2b[[2]], rep(NA, max_length - length(title2b[[2]])))
text2b[[2]] <- c(text2b[[2]], rep(NA, max_length - length(text2b[[2]])))

canvas9 <- data.frame(Category = ca17,
                     Product_number = producto17,
                      Name_of_Product = produc17,
                      Userame = namez17,
                       Rating = ratingz17,
                       Date = dates2b[[2]],
                       Title_of_Review = title2b[[2]],
                       Text_of_Review = text2b[[2]],
                       stringsAsFactors = FALSE
                       )
head(canvas9, 50)
canvas9 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```
```{r}
nama18 <- names2b[[3]]
namez18 <- nama18[!grepl("NA", nama18, ignore.case = TRUE)]
namez18 <- namez18[-(1:2)]
producto18 <- productnumber2b[[3]]
producto18 <- rep(producto18, length.out = length(namez18))
produc18 <- nameofproduct2b[[3]]
produc18 <- rep(produc18, length.out = length(namez18))
cater18 <- category2b[[2]]
ca18 <- rep(cater18, length.out = length(namez18))

ratingz18 <- ratings2b[[1]]
    if (length(ratingz18) > length(namez18)) {
    ratingz18 <- tail(ratingz18, length(namez18)) 
    } else if (length(ratingz18) < length(namez18)) {
    ratingz18 <- c(ratingz18, rep(NA, length(namez18) - length(ratingz18)))
    }
```
```{r}
max_length <- max(
  length(ca18),
  length(producto18),
  length(produc18),
  length(namez18),
  length(ratingz18),
  length(dates2b[[3]]),
  length(title2b[[3]]),
  length(text2b[[3]])
)

ca18 <- c(ca18, rep(NA, max_length - length(ca18)))
producto18 <- c(producto18, rep(NA, max_length - length(producto18)))
produc18 <- c(produc18, rep(NA, max_length - length(produc18)))
namez18 <- c(namez18, rep(NA, max_length - length(namez18)))
ratingz18 <- c(ratingz18, rep(NA, max_length - length(ratingz18)))
dates2b[[3]] <- c(dates2b[[3]], rep(NA, max_length - length(dates2b[[3]])))
title2b[[3]] <- c(title2b[[3]], rep(NA, max_length - length(title2b[[3]])))
text2b[[3]] <- c(text2b[[3]], rep(NA, max_length - length(text2b[[3]])))

canvas10 <- data.frame(Category = ca18,
                     Product_number = producto18,
                      Name_of_Product = produc18,
                      Userame = namez18,
                       Rating = ratingz18,
                       Date = dates2b[[3]],
                       Title_of_Review = title2b[[3]],
                       Text_of_Review = text2b[[3]],
                       stringsAsFactors = FALSE
                       )
head(canvas10, 50)
canvas10 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```